### ISSUE TITLE
script auto closes

### ISSUE THREAD

**Issue by Rademenes16** [Deadshot0x7/007-TheBond#17]
Im searching for a name (option 2) and the window closes itself after few seconds. 
By the way, some options like number and IP address don't work either.

OS - parrot home

**Comment by Deadshot0x7** [comment]
which python version do you use?

**Comment by Rademenes16** [comment]
Always the newest one. Script executes fine, it's just closing itself after few seconds.

**Comment by Deadshot0x7** [comment]
okay , I fix it
