### ISSUE TITLE
Write for us

### ISSUE THREAD

**Issue by thexwts** [Deadshot0x7/007-TheBond#2]
I'm sorry for writing here but it was the only way to contact you,
You are good in the cybersecurity field? Then you can write for us about your own tool on GitHub and the use of it.
Your article will be published with your name and a link to your website and social media accounts if you want. Please reply to us at Email: kalitutwrite @ gmail.com
Walid Salame
kalitut .com
Twitter:@xKaliSec

**Comment by Deadshot0x7** [comment]
Hey, I'm interested to write a blog on your website, But I'm a bit busy right now, I will contact you soon

**Comment by thexwts** [comment]
OK :)
