### ISSUE TITLE
python 007-TheBond.py

### ISSUE THREAD

**Issue by Jotar0Kuj0** [Deadshot0x7/007-TheBond#24]
Hello! Got a trouble here. Installed git and script, then venv and all packages including last pip and others, but after using "python 007-TheBond.py" command, encountered an error "no such file or directory", Screenshots included. So, can I get some tech advice? 
![IMG_20220605_232145_957](https://user-images.githubusercontent.com/106929174/172067096-5a276781-d411-4980-a905-47a9b4d16d29.jpg)

**Comment by Deadshot0x7** [comment]
the script is inside the src folder
