### ISSUE TITLE
MacOS: Not working.

### ISSUE THREAD

**Issue by viktorg1** [Deadshot0x7/007-TheBond#26]
It doesn't seem to crash or anything, the script runs. I tested to see if any of the given checkers work.

I tried to run and check the script out by giving some usernames phone numbers and IP Addresses. It doesn't seem to give any return, in fact all it does is return something(which my eyes can't see) and in 0.1 seconds the screen clears and shows me the menu again. I don't know if this is MacOS error or it's a script bug.

**Comment by Deadshot0x7** [comment]
Hey use python2 instead of python3
