### ISSUE TITLE
Não consigo

### ISSUE THREAD

**Issue by Adalberto069** [Deadshot0x7/007-TheBond#27]
Não consigo executar a escript no termux

**Comment by Deadshot0x7** [comment]
> Não consigo executar a escript no termux

use python2 instead of python3

**Comment by Adalberto069** [comment]
Continua dando erro


d.py07-TheBond]────►python2 007-TheBon
python2: can't open file '007-TheBond.py': [Errno 2] No such file or directory

**Comment by Deadshot0x7** [comment]
cd src and then python2 007-TheBond.py
