### ISSUE TITLE
help troubleshoot erros 

### ISSUE THREAD

**Issue by highrider0602** [Deadshot0x7/007-TheBond#31]
This is what I am met with when using any of the options in 007, 

![007-errior](https://user-images.githubusercontent.com/62209183/209151347-8adcbff6-f6d0-487a-96e3-ae2ab7f232e6.png)

I installed by running the setup.sh, which had no errors when run, followed it with an install of the requirements.txt file

changed to the src directory and ran the tools 
python3 007-thebond.py and
python3 007-TheBond.py and each option I select from there has an error

Option 1 -Instagram, described above with the attached image.

Option 2 works for search, and it pulls up relevant results, but it clears them off the screen before I can do anything with it, it will hang for 5 seconds then clear back to the main menu of the tool. 

Phone lookup tool lets you type your input but just refreshed back to the main menu, and I've tried entering the
number in the proper format and Varangians for instance with this scenario I used my own number, and it would just do the same thing. 

IPlookup option also does the same thing. Just flashes back to the main menu of the tool and doesn't throw an error, doesn't even show any output at all.

Any advice is appreciated.

**Comment by Deadshot0x7** [comment]
@highrider0602 , use Python2 insted of python3
