### ISSUE TITLE
Package issues 

### ISSUE THREAD

**Issue by PHILnony** [Deadshot0x7/007-TheBond#47]
I have tried to install the requirements package but some were unsuccessful
Here are the packages I can't install even with pip. 
from Search import Websearch
from PhoneLookup import Lookup
from SearchUsername import SearchUsername 
from EmailLookup import EmailLookup
Please if the name of the packages have been changed please I need your assistance.
Thank you

**Comment by Deadshot0x7** [comment]
@PHILnony  , thanks for the bringing the attention to the issue , the issue has been fixed and should reflect to you repo  & thanks for the considering  my tool !
