### ISSUE TITLE
PIP package and required python version

### ISSUE THREAD

**Issue by StepAndy** [Deadshot0x7/007-TheBond#49]
1. What is "email-validate # for email validation"? I can't find it in pip
2. Also, which python version is preferred?

Thanks

**Comment by Deadshot0x7** [comment]
@StepAndy  , Thanks for bringing our attention towards the issue and here's the solution to the problem 

- For the package , you can find it on [pypi](https://pypi.org/)
- For the Python Version , I would recommend to use python 3.2 

**And if you loved this tool  , please star it and join the discord server**

**Comment by StepAndy** [comment]
At least
1) There is no "email-validate" in PyPi
2) Python 3.2 doesn't support venv

**Comment by Deadshot0x7** [comment]
Try these 
- pip install validate-email-address
- Try python 2.7

**Comment by Innocentmonster23** [comment]
I also try to hack Instagram account but I m always failed

**Comment by Deadshot0x7** [comment]
Instagram has changed the way how it's url works , so yeah it's don't be working for a while
