### ISSUE TITLE
ERROR: No matching distribution found for email-validate

### ISSUE THREAD

**Issue by cbspidi** [Deadshot0x7/007-TheBond#50]
Hello 
Are you using some deprecated email validation package?

ERROR: Could not find a version that satisfies the requirement email-validate (from versions: none)
ERROR: No matching distribution found for email-validate

Traceback (most recent call last):
  File "007-TheBond/scripts/007-TheBond.py", line 12, in <module>
    from EmailLookup import EmailLookup
  File "scripts/EmailLookup.py", line 2, in <module>
    from email_validate import validate
ModuleNotFoundError: No module named 'email_validate'

**Comment by Deadshot0x7** [comment]
Follow the instructions of issue #49
