### ISSUE TITLE
email-validate

### ISSUE THREAD

**Issue by Loardclasher** [Deadshot0x7/007-TheBond#54]
while using the command 'pip install -r requirements.txt' I am just running into this error: 

ERROR: Could not find a version that satisfies the requirement email-validate (from versions: none)
ERROR: No matching distribution found for email-validate

I have upgraded my pip and python to the latest still have to problem.

**Comment by Deadshot0x7** [comment]
Thanks  for the reporting the error , the issued have been fixed with issue #49 , you can find the solution  over there
