### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shobhitparvan** [Deadshot0x7/007-TheBond#9]
$~/007-TheBond> python -m venv venv
/usr/bin/python: No module named venv
$~/007-TheBond> source venv/bin/activate
bash: venv/bin/activate: No such file or directory

was this supposed to happen?
I am running opensuse tumbleweed [gnome 40]

and in the end "python 007-TheBond.py" the script 007-TheBond.py wasn't found
[file4.txt](https://github.com/Deadshot0x7/007-TheBond/files/6537217/file4.txt)

**Comment by Deadshot0x7** [comment]
Don't use virtual env  for running the script

**Comment by shobhitparvan** [comment]
Then what should I do
 After neglecting it in the there is no script named 007-TheBond.py?

Please resolve this.

**Comment by Deadshot0x7** [comment]
have you changed the directory to the src?

**Comment by shobhitparvan** [comment]
No, I thought the file would be there in 007-TheBond directory

**Comment by Deadshot0x7** [comment]
after getting into the directory move src  directory, there you'll find the  007-TheBond

**Comment by Joh2019** [comment]
what is a src directory

**Comment by Deadshot0x7** [comment]
> what is an
 src directory

src  dir is the file that contain the application script

**Comment by Joh2019** [comment]
why it has an error while install 007 TheBond in termux...

**Comment by Deadshot0x7** [comment]
@Joh2019  can you upload the photo or screenshot of the error ?
